### PR TITLE
Fix portal auth handoff and remaining Access bugs

### LINKED ISSUE #196: [Infra] Expand Railway watch patterns to cover all API build inputs
﻿## Problem
The Railway service config watches only part of the API build input set, so build-affecting changes can be missed by the deploy trigger.

## Why This Is A Bug
`apps/api/railway.json` gates rebuilds through `watchPatterns`, but the current list omits inputs such as `bun.lock` and other manifest-level build inputs. A dependency or shared-package manifest change can alter the API build while bypassing the watch filter, leaving Railway on stale code until some unrelated watched file changes.

## Current Evidence
- `apps/api/railway.json` watches `apps/api/**`, `packages/shared/**`, `package.json`, `apps/api/package.json`, and `tsconfig.base.json`.
- The API build still depends on workspace-level dependency resolution from `bun.lock`.

## Expected Fix
Expand the watch list to cover every build input that can change the produced API artifact, or remove the path filter if Railway cannot safely model the full dependency set.

## Introduced By
- PR #171
- Carried forward by PR #172

Depends on: none.

### LINKED ISSUE #197: [Backend] Align published API catalogs with implemented routes
﻿## Problem
The shared API catalogs and ops docs still publish a larger live backend surface than the Fastify server actually registers.

## Why This Is A Bug
`@paretoproof/shared` currently advertises `/public/*`, `/portal/access-requests*`, `/portal/runs*`, and `/internal/*` endpoints, and the operations docs describe the `/internal/*` service-token boundary as already live. On current `main`, the server only registers `/health`, `/portal/me`, and `/portal/admin/access-requests`. Any consumer that treats the shared package or docs as the source of truth will target routes that deterministically 404, and ops work can assume an internal boundary that the API does not implement.

## Current Evidence
- `packages/shared/src/contracts/api-catalog.ts`
- `packages/shared/src/contracts/api-call-boundary.ts`
- `docs/operations-baseline.md`
- `apps/api/src/server/build-server.ts`
- `apps/api/src/routes/portal.ts`
- `apps/api/src/routes/admin.ts`

## Expected Fix
Either implement the published routes and internal service-token auth path, or mark those entries as planned and remove them from the live contract exports and ?current baseline? documentation.

## Introduced By
- PR #179
- PR #182
- PR #183
- PR #184
- PR #190

Depends on: none.

### LINKED ISSUE #235: [Backend] Approved users cannot recover from a new Cloudflare Access subject
Introduced by PR #229 (`Add the portal self-service access-request API`) and reinforced by PR #231 (`Add portal profile API endpoints`), both of which only received Codex usage-limit replies and have no newer fix on `main`.

The current account-resolution flow only treats a caller as approved when `user_identities.provider_subject` already matches the current Access JWT subject. If an already-approved contributor signs in through a different Cloudflare Access subject, `resolveAccessRbacContext()` falls back to `status: denied, reason: access_request_required` even when the same email already owns active role grants.

The self-service recovery path cannot fix this:
- `POST /portal/access-requests` upserts the existing user by email, but then throws `already_approved` as soon as it sees active role grants, so the transaction rolls back and the new identity link is never saved.
- `GET/PATCH /portal/profile` also look up the caller by `provider_subject` only, so the newly signed-in approved user cannot inspect or repair their account from the portal.

Reproduction:
1. Approve a contributor so they have an active `role_grants` row.
2. Sign in as that same person through a different Cloudflare Access subject (for example a second provider or any subject rotation).
3. `GET /portal/me` returns denied instead of approved.
4. `POST /portal/access-requests` returns `409 already_approved`, and `/portal/profile` remains uninitialized.

Impact:
- Already-approved admins, collaborators, or helpers can lock themselves out by changing Access provider/subject.
- The current portal has no self-service path to attach the new identity or recover access.
- Issue #225 scopes future multi-provider linking, but this is already a live authorization regression for any approved user whose Access subject changes.

### LINKED ISSUE #248: [Backend] Prevent duplicate pending access requests under concurrent submission
﻿The self-service access-request flow added in PR #229 is still vulnerable to duplicate pending rows under concurrent submission.

Affected code:
- `apps/api/src/routes/portal.ts:230-320`
- `apps/api/src/db/schema.ts:125-149`

Failure mode:
1. The same authenticated caller submits `/portal/access-requests` twice in parallel (double-click, retry, replay, or two tabs).
2. Both transactions upsert the same `users` row.
3. Both transactions query for the latest request and can observe "no pending request" before either insert commits.
4. Both transactions then execute the insert at `apps/api/src/routes/portal.ts:305-313`.
5. The queue ends up with multiple pending `access_requests` rows for the same email/user.

Impact:
- Admins can review and act on stale duplicate requests for the same identity.
- The approval queue loses its single-source-of-truth property.
- The decision-race problem in PR #245 becomes easier to hit because there are now multiple pending records for one caller.

Why this is still open:
- No later PR through #246 adds a unique constraint for pending requests or rewrites the handler as an atomic upsert.

Suggested fix:
- Add a partial unique index for one pending request per normalized user/email.
- Replace the current read-then-insert flow with an atomic upsert/conditional update keyed on that constraint.

### LINKED ISSUE #273: [Backend] Pending access-request resubmission can flood audit_events without changing state
﻿A caller with an already-pending access request can generate an unbounded number of `access_request.submitted` audit rows without changing any approval state.

Why this is a problem:
- In `apps/api/src/routes/portal.ts`, the pending-request update branch (`lines 357-382`) updates the existing request in place and then always inserts a fresh `audit_events` row.
- The create branch (`lines 385-414`) also inserts an audit row, but there is no rate limit, dedupe key, or cooldown on resubmission.
- Once a caller is in `pending`, repeated identical POSTs to `/portal/access-requests` keep appending audit rows while the underlying `access_requests` record stays the same.

Impact:
- A single authenticated caller can flood `audit_events` with low-value `access_request.submitted` entries.
- That creates write amplification, noisy review history, and avoidable database growth without changing authorization state.
- It also makes it harder to audit genuinely meaningful contributor-state transitions.

Reproduction:
1. Submit one access request so the caller has a `pending` row.
2. Repeat `POST /portal/access-requests` with the same payload in a loop.
3. The same pending request is updated in place, but each call inserts another `access_request.submitted` row.

This behavior was introduced when PR #262 added submission audit logging on top of the PR #229 access-request flow. As of 2026-03-09 there is no later PR adding a cooldown, dedupe rule, or other abuse guard.

Suggested fix:
- Only emit a new submission audit event when the request meaningfully changes, or rate-limit/cool down resubmissions.
- Alternatively, record a single mutable "last resubmitted" timestamp on the request instead of appending one audit row per identical retry.

### LINKED ISSUE #274: [Backend] Admin access-request queue can strand pending requests behind reviewed rows
﻿The admin access-request queue can permanently hide actionable pending requests once the table grows beyond 50 rows.

Why this is a problem:
- `apps/api/src/routes/admin.ts` reads the queue with `findMany({ limit: 50, orderBy: [desc(accessRequests.createdAt)] })` (`lines 48-51`).
- The query does not filter to `status = 'pending'` and it does not expose pagination or cursor parameters.
- The portal admin UI only operates on the rows returned by that endpoint (`apps/web/src/routes/portal-access-request-panel.tsx`).

Impact:
- If the newest 50 rows are already approved/rejected, an older pending request never appears in the UI.
- Admins cannot approve or reject that stranded request from the current product surface even though it is still actionable in the database.
- A modest amount of review history can therefore deadlock contributor onboarding.

Reproduction:
1. Create more than 50 `access_requests` rows.
2. Leave an older request in `pending`.
3. Add enough newer approved/rejected rows so the old pending row falls outside the newest 50.
4. Call `GET /portal/admin/access-requests` or load the admin queue UI.
5. The pending row is unreachable because the API never returns it.

This behavior was introduced in PR #245 and exposed in PR #246. As of 2026-03-09 there is no later PR adding a pending-first filter or pagination.

Suggested fix:
- Either return pending rows first, or add explicit status filters plus pagination/cursor support.
- The admin UI should be able to reach every pending request, not just the newest 50 rows overall.

### LINKED ISSUE #275: [Backend] Public and auth origins still have credentialed CORS access to the portal API
﻿The API still replies with credentialed CORS headers to `https://paretoproof.com` and `https://auth.paretoproof.com`, not just `https://portal.paretoproof.com`.

Why this is a problem:
- `apps/api/src/server/build-server.ts` currently defaults `CORS_ALLOWED_ORIGINS` to the public site, auth entrypoint, and portal (`lines 22-25`) and enables `credentials: true` (`line 46`).
- The public and auth surfaces do not need direct API access. The current web code only calls the API from portal code paths (`apps/web/src/routes/portal-bootstrap.tsx`, `apps/web/src/routes/portal-access-request-panel.tsx`, and `apps/web/src/routes/portal-profile-panel.tsx`).
- `apps/web/src/routes/public-site.tsx` and `apps/web/src/routes/auth-entry.tsx` only build navigation/redirect links; they never fetch the API.

Impact:
- Any XSS or injected script on the public marketing site or auth redirect surface can immediately read and mutate the credentialed portal API with the victim's Cloudflare Access cookies.
- That unnecessarily widens the blast radius from a public-surface compromise to admin-only routes like `/portal/admin/access-requests/*`.

Reproduction:
1. Load any script in the origin `https://paretoproof.com` or `https://auth.paretoproof.com`.
2. Issue `fetch("https://api.paretoproof.com/portal/me", { credentials: "include" })`.
3. The API accepts the origin because it is on the default allowlist.

This behavior was introduced in PR #257 and is still present after PR #267. As of 2026-03-09 there is no later PR narrowing the production allowlist back down to the portal origin.

Suggested fix:
- Restrict production credentialed CORS to `https://portal.paretoproof.com` only.
- Keep localhost development behind `CORS_ALLOW_LOCALHOST=true`.
- If the public or auth surfaces ever need API access later, grant that explicitly per-route rather than globally.

### LINKED ISSUE #280: [Backend] PR #276 hardcodes recovered and newly linked identities to cloudflare_one_time_pin
﻿PR: #276

The new recovery/linking flow does not carry the caller's actual Cloudflare Access provider through to persistence.

Affected code:
- `apps/api/src/auth/cloudflare-access.ts:10-14` only preserves `{ email, issuer, subject }` from the Access assertion.
- `apps/api/src/routes/portal.ts:403-407` hardcodes every newly linked identity as `cloudflare_one_time_pin`.
- `apps/api/src/routes/portal.ts:613-614`, `626`, and `659` hardcode recovery requests the same way.

Impact:
- A GitHub- or Google-backed Access login accepted through the new auth surface will be stored as `cloudflare_one_time_pin` in `user_identities` / `access_requests`.
- The portal profile will show false provider metadata.
- Any later provider-aware linking, auditing, or recovery logic will be operating on corrupted identity records instead of the real provider type.

Because the wrong provider value is persisted, fixing this later requires data repair, not just a code change.

This is not covered by open issues #270-#275.

### LINKED ISSUE #281: [Frontend] auth.paretoproof.com access-start handlers fail closed and return 502 in production
﻿PRs: #278, #279

`apps/web/functions/_shared/access-start.ts:48-111` moves the Cloudflare Access/OAuth start handshake into a Pages Function, but the handler never produces a browser-owned Access transaction.

What the code does now:
- `resolveAccessLoginUrl()` fetches `https://portal.paretoproof.com{redirect}` server-side and expects Cloudflare Access to answer with a `302` login redirect.
- `resolveProviderUrl()` then fetches the Access login page server-side, scrapes a provider URL out of the HTML, and returns `302` to that provider URL.
- The function never forwards any Access `Set-Cookie` or state from the server-side handshake back to the browser.

Why this is broken:
- In production today, `https://portal.paretoproof.com/` returns `200`, not an Access `302`, so line 54 throws `Expected Access redirect, received 200.` and both start handlers fail immediately.
- Even if the protected-resource assumption were corrected, the browser still would not own the Access session / CSRF state because the entire pre-provider handshake happened on the server.

Reproduction on 2026-03-10:
- `curl -sS -D - https://auth.paretoproof.com/api/access/start/github?redirect=%2F -o -`
- `curl -sS -D - https://auth.paretoproof.com/api/access/start/google?redirect=%2F -o -`
- Both currently return `502 Bad Gateway`.

Impact:
- The new auth surface cannot start a working GitHub or Google sign-in flow in production.
- Contributor login is effectively down behind the merged auth-surface rollout.

### LINKED ISSUE #282: [Backend] PR #276 can commit identity-recovery requests as approved before link validation finishes
﻿PR: #276

`apps/api/src/routes/admin.ts:121-170` updates an `identity_recovery` request to `status = 'approved'` before validating whether the requested identity can actually be linked.

Current control flow:
- Lines 122-137 update the request row to `approved`.
- Lines 155-170 only afterwards check that the recovery request has a subject/provider and that the requested subject is not already owned by a different user.
- On those validation failures, the transaction returns `{ kind: "conflict" }` instead of throwing.

That means the transaction can commit with:
- `access_requests.status = 'approved'`
- no new `user_identities` row
- no repaired access for the locked-out user

Impact:
- The pending recovery request disappears from the admin queue even though nothing was linked.
- The admin UI receives a 409, but the request is no longer actionable.
- If the conflicting subject is already linked elsewhere, the user can be left in `identity_recovery_required` with no surviving pending row to review.

This is not covered by open issues #270-#275.

### LINKED ISSUE #283: [Backend] Admin approval can grant roles to users that still have no linked Access identity
**Affected PRs:** #245 (merged), still present on `main`, and still present in open PR #276.

`/portal/admin/access-requests/:accessRequestId/approve` resolves a target user and inserts an active `role_grants` row, but it never verifies that a normal `access_request` already has a linked `user_identities` record.

On `main`, the problem is in `apps/api/src/routes/admin.ts:98-178`: once `targetUser` is found, the handler revokes/regrants roles and returns success without checking `user_identities` at all. The auth path in `apps/api/src/auth/resolve-access-rbac-context.ts:66-163` still requires the current `provider_subject` to resolve through `user_identities` before an approved role can ever be used.

That means any pending request created manually, migrated from an older flow, or otherwise missing a linked identity can be marked `approved` and given an active role grant while the contributor is still denied at `/portal/me`.

**Reproduction**
1. Insert or retain a pending `access_requests` row for a user/email that has no matching `user_identities` row.
2. Approve it through `/portal/admin/access-requests/:accessRequestId/approve`.
3. The endpoint returns success and creates an active role grant.
4. The caller still resolves as denied because RBAC lookup cannot find a linked Access subject.

**Impact**
Admins can believe onboarding succeeded when the account is still unusable. Because PR #276 only special-cases `identity_recovery`, the same blind spot remains for ordinary `access_request` approvals there as well.

**Suggested fix**
Before approving a normal `access_request`, require an existing linked identity for the target user (or convert the approval path into an explicit identity-linking flow). If the request lacks a linkable identity, fail the approval instead of granting a role that cannot be exercised.

### LINKED ISSUE #284: [Backend] /portal/access-requests/me still hides rejected or withdrawn email-only requests
**Affected PRs:** #269 (merged); still broken on `main`, and still incomplete in open PR #276.

`/portal/access-requests/me` is supposed to show the caller's latest access-request state, but the current handler only falls back to an email-based lookup when the caller is already in a `pending` context.

On `main`, the regression starts at `apps/api/src/routes/portal.ts:108-150`: the route is guarded by `pending_or_approved`, so any authenticated caller whose email-only state resolves to `denied` never reaches the handler at all.

PR #276 widens the guard back to `authenticated_access_identity`, but the handler at `apps/api/src/routes/portal.ts:166-187` still only does the email fallback when `accessContext.status === "pending"`. For unlinked identities whose latest request was reviewed and rejected/withdrawn, the handler still returns `{ item: null }`.

That is inconsistent with `apps/api/src/auth/resolve-access-rbac-context.ts` on both branches: the denied `rejected_or_withdrawn` state is already being derived from the latest request by normalized email (`main`: lines 134-145, PR #276: lines 180-189).

**Reproduction**
1. Submit an access request from a new identity so the request exists by email, but do not create or keep a `user_identities` link for that subject.
2. Have an admin reject or withdraw the request.
3. Call `/portal/access-requests/me` as the same authenticated email.
4. The API returns 403 on `main`, and still returns `{ item: null }` on PR #276, even though the same email just resolved to `rejected_or_withdrawn`.

**Impact**
Rejected or withdrawn applicants cannot retrieve their own `decisionNote`, `reviewedAt`, or latest request status through the documented endpoint. The portal has no reliable API path to explain why a request was denied, and clients see ?no request? instead of the actual reviewed record.

**Suggested fix**
When there is no linked identity, fall back to the latest request by normalized email for any authenticated caller with an asserted email, not just pending callers. Another option is to have RBAC resolution attach the relevant request id/status for denied email-based states so the endpoint can load the exact record.

### LINKED ISSUE #286: [Frontend] PR #276 gates portal bootstrap on tab-local session markers instead of the real Access session
**Affected PR:** #276

`apps/web/src/routes/portal-bootstrap.tsx:86-151` skips the `/portal/me` bootstrap request unless either:
- `window.sessionStorage.portalAccessReady === '1'`, or
- the current URL still carries `?access_session=1`.

That is not a reliable proof of an active Cloudflare Access session. `sessionStorage` is tab-scoped, and the `access_session` query flag is stripped immediately at `apps/web/src/routes/portal-bootstrap.tsx:236-243`.

**Reproduction**
1. Complete one successful portal login so the app writes `sessionStorage.portalAccessReady = '1'`.
2. Close that tab but keep the Cloudflare Access cookie/session alive.
3. Open `https://portal.paretoproof.com/` from a bookmark, a deep link, or a new tab.
4. The bootstrap effect hits the early `setState({ status: 'unauthenticated' })` branch at lines 146-151 instead of calling `/portal/me`, so the user is forced back through the auth redirect even though the Access session is still valid.

**Impact**
- Direct portal entry in a fresh tab/session regresses for already-authenticated users.
- Deep links can bounce through the login surface unnecessarily.
- The branch is using client-side tab state as an auth gate instead of asking the API for the real session state.

**Suggested fix**
Always attempt `/portal/me` on non-local portal loads and let the backend return `401` when the Access session is actually missing. If you still want a client hint, treat it only as an optimization after a real API check, not as a prerequisite for one.

### LINKED ISSUE #288: [Backend] Approving a stale pending access request can silently downgrade an already-approved user
## Summary
Approving an old pending access request can silently revoke a user's current grant and replace it with the role that was requested in the stale queue item.
## Evidence
- pps/api/src/routes/admin.ts:181-242 loads current active role grants, revokes all of them, and inserts pprovedRole from the request.
- The route never rejects a normal pending request when the target user already has an active grant from a newer approval path.
## Impact
A stale helper/collaborator request can downgrade an already-approved collaborator/admin if that queue item is approved later. The API treats the stale request as authoritative instead of detecting that the user's access level has already changed.
## Minimal reproduction
1. User opens a pending access request asking for helper.
2. Before that request is reviewed, the same user receives collaborator or dmin access through another path.
3. An admin later approves the old pending request.
4. The route revokes the current grant and replaces it with the stale requested role.
## PR lineage
- Introduced by PR #245.
- Still present on main and in open PR #287.
- I did not find a newer PR that fixes it.

### LINKED ISSUE #289: [Backend] PR #287 treats profile-link start URLs as bearer tokens for account linking
## Summary
PR #287 turns the profile-link startUrl into a bearer capability: possession of the URL is enough to redeem the victim's pending link intent.
## Evidence
- pps/api/src/routes/portal.ts:112-125 builds https://auth.paretoproof.com/api/access/start/{provider}?link_intent=<uuid>.
- pps/web/functions/_shared/access-start.ts:229-246 accepts link_intent straight from the query string and signs it into PortalLinkIntent without authenticating the caller.
- pps/api/src/routes/portal.ts:209-275 later trusts that cookie plus the Access login and binds the resulting subject to intentRow.userId.
## Impact
If the startUrl leaks within its 10-minute lifetime, another user can authenticate with the target provider and attach their own Access subject to the victim account. The callback does not bind the intent to the portal session, browser instance, or initiating user.
## Minimal reproduction
1. User A creates a link intent and obtains the returned startUrl.
2. User B obtains that URL before it expires.
3. User B opens the URL, completes the matching GitHub/Google login, and the callback links User B's Access identity to User A's user_id.
## PR lineage
- Introduced by PR #287.
- I did not find a newer PR that fixes this.

### LINKED ISSUE #290: [Backend] PR #287 makes /portal/session/complete vulnerable to cross-site request forgery
## Summary
/portal/session/complete performs account-link side effects on GET, while PR #287 also makes the relevant cookies cross-site.
## Evidence
- pps/web/functions/_shared/access-start.ts:81-87 rewrites CF_AppSession to Domain=.paretoproof.com; Path=/; SameSite=None.
- pps/web/functions/_shared/access-start.ts:158-166 sets PortalLinkIntent with the same cross-site cookie scope.
- pps/api/src/routes/portal.ts:195-282 uses those cookies on GET /portal/session/complete to insert/update user_identities, mark the link intent used, clear cookies, and redirect.
## Impact
A third-party page can force-complete or invalidate a pending identity-link flow by navigating the victim to https://api.paretoproof.com/portal/session/complete?... while those cookies are present. That is a live CSRF on account-linking state.
## Minimal reproduction
1. Start a profile link flow so the browser has CF_AppSession, PortalAccessProvider, and PortalLinkIntent.
2. Visit an external page that embeds or redirects to https://api.paretoproof.com/portal/session/complete?redirect=/profile.
3. The browser sends the cookies cross-site, and the API mutates link state without any origin check or one-time state parameter in the URL.
## PR lineage
- Introduced by PR #287.
- I did not find a newer PR that fixes this.

### LINKED ISSUE #291: [Backend] Self-service access requests become orphaned when a linked subject's Access email changes
## Summary
A linked Access subject can end up with a permanently orphaned access request when its current Access email no longer matches any users.email row.
## Evidence
- pps/api/src/routes/portal.ts:571-622 only treats existingIdentity.userId !== matchingUser.id as a conflict when matchingUser exists.
- If existingIdentity exists but matchingUser is null, the route inserts a brand-new users row and stores the request under that new user_id.
- pps/api/src/auth/resolve-access-rbac-context.ts:82-136 still resolves authorization through the original providerSubject link.
- pps/api/src/routes/admin.ts:143-153 then rejects approval for the orphaned request with ccess_identity_link_required because the new user has no linked identity.
## Impact
The requester cannot see or advance the new pending request through their linked identity, and admins cannot approve it. The request is stranded behind a synthetic user record.
## Minimal reproduction
1. Create a linked identity for user A.
2. Change the Access email for that same subject so it no longer matches users.email for user A.
3. Submit /portal/access-requests.
4. The API creates user B, records the request against user B, but keeps the subject linked to user A.
## PR lineage
- Introduced by PR #258 as part of the self-service linking hardening.
- Still present on main and in open PR #287.
- I did not find a newer PR that fixes it.

### LINKED ISSUE #292: [Backend] PR #287 lets rejected identity-recovery requests reopen indefinitely
## Summary
Rejected or withdrawn identity-recovery attempts are not terminal. The same unlinked Access subject can reopen recovery indefinitely after an admin has already denied it.

## Evidence
- `apps/api/src/auth/resolve-access-rbac-context.ts:155-177` returns `reason: identity_recovery_required` for approved email matches whenever there is no pending recovery row; it never treats a rejected or withdrawn recovery request as final.
- `apps/api/src/routes/portal.ts:828-889` lets `/portal/access-recovery` update or create an `identity_recovery` request whenever the caller still matches an approved email.
- Unlike the normal access-request flow at `apps/api/src/routes/portal.ts:650-655`, the recovery path has no guard that blocks re-entry after `rejected` or `withdrawn` status.

## Impact
An admin rejection does not actually end the recovery attempt. The same subject can immediately resubmit and keep reappearing in the queue, creating repeated social-engineering opportunities and eroding the meaning of the rejection decision.

## Minimal reproduction
1. Start an `identity_recovery` request for an approved email whose current Access subject is unlinked.
2. Reject that request through `/portal/admin/access-requests/:accessRequestId/reject`.
3. Sign back in as the same unlinked subject and load the portal again.
4. `resolveAccessRbacContext()` still returns `identity_recovery_required`, and `POST /portal/access-recovery` creates a fresh pending recovery request.

## PR lineage
- Introduced by commit `d430ad7` (`Add safe approved-user identity recovery flow`) in open PR #287.
- I did not find a newer PR that fixes it.

### LINKED ISSUE #293: [Frontend] PR #287 turns portal bootstrap network failures into auth redirect loops
## Summary
PR #287 turns production `/portal/me` network failures into `unauthenticated` state and immediately bounces the browser back to the auth entrypoint.

## Evidence
- `apps/web/src/routes/portal-bootstrap.tsx:97-99` classifies any browser `TypeError` whose message matches `fetch` as an `isAccessBootstrapMiss`.
- `apps/web/src/routes/portal-bootstrap.tsx:177-185` catches that condition and calls `setState({ status: unauthenticated })` instead of surfacing an error.
- `apps/web/src/routes/portal-bootstrap.tsx:201-207` then redirects every `unauthenticated` state to `buildAuthUrl(currentRelativeUrl)`.

## Impact
Any transient API outage, DNS miss, TLS failure, blocked CORS preflight, or other production fetch error is misreported as “sign in again” rather than a real portal outage. Users can get trapped in an auth redirect loop while the underlying availability incident stays hidden.

## Minimal reproduction
1. Load `https://portal.paretoproof.com/` on a branch with PR #287.
2. Cause `fetch(${apiBaseUrl}/portal/me)` to fail at the network layer (for example by blocking `api.paretoproof.com`, breaking CORS, or forcing a TLS/DNS miss).
3. The catch path sets `status: unauthenticated`.
4. The next effect redirects back to `https://auth.paretoproof.com/...` instead of showing the existing error UI.

## PR lineage
- Introduced by commit `1c6a9cc` (`Rely on Access session for portal bootstrap`) in open PR #287.
- I did not find a newer PR that fixes it.

### PR DESCRIPTION
**Pull request by Tomodovodoo**
## Summary
- route portal auth through the protected API audience and make unauthenticated portal entry fall back to the branded auth surface instead of the hosted Access page or a failed bootstrap screen
- persist a signed provider hint across the auth handoff so new identities and recovery requests keep the real GitHub/Google provider instead of being stamped as OTP
- harden admin approval, request lookup, and recovery state flows so stale approvals are rejected, linked identities stay attached through email drift, and rejected recovery attempts cannot reopen immediately

## Live changes validated
- `api.paretoproof.com` is back behind the Cloudflare proxy so Access can enforce `/portal/*`
- `auth.paretoproof.com/api/access/start/{github,google}` now return live provider redirects instead of `502`
- direct unauthenticated navigation to `https://portal.paretoproof.com/profile` now lands on the branded auth page
- the current branch commit was deployed to Railway for live verification

## Validation
- `bun run typecheck:shared`
- `bun run typecheck:api`
- `bun run typecheck:web`
- `bun run build:shared`
- `bun run build:api`
- `bun run build:web`
- Playwright live checks for `auth.paretoproof.com`, provider redirects, and direct `portal.paretoproof.com/profile`
- OS-level screenshot capture of the live auth surface

Closes #196
Closes #197
Closes #235
Closes #248
Closes #273
Closes #274
Closes #275
Closes #280
Closes #281
Closes #282
Closes #283
Closes #284
Closes #286
Closes #288
Closes #289
Closes #290
Closes #291
Closes #292
Closes #293

### CODE REVIEW

**Comment by Tomodovodoo** [comment]
Addressed the earlier Codex inline findings in the follow-up auth-handoff commits and pushed the final recovery-state fix in 866a196. A fresh @codex review request is posted on the PR, but the connector is currently quota-limited and has not produced new inline feedback.
